### ISSUE TITLE
bodyparser.json() shown as deprecated? (question)

### ISSUE THREAD

**Issue by hootyjeremy** [expressjs/body-parser#434]
I'm using 6.14.11 for express/body-parser and when I include `app.use(bodyParser.json())` from the express documentation, vscode crosses it out and says it's deprecated. However, it does still seem to work and I get a body object in a POST. 

Is this no longer the correct way to use body-parser?

**Comment by dougwilson** [comment]
I'm not sure why it would show as deprecated, but no, it is not. You may want to report thia to them to see what the issue is. I don't think it would be an issue with the code in the repo as we have not published a new version in a while now. If you find out we need to change something this, please let us know.

**Comment by karltaylor** [comment]
I am getting this too when using typescript.

After doing some digging, it looks like it's coming from here, 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/body-parser/index.d.ts#L19

After doing some more digging, there was an older comment:

```
/**
 * bodyParser: use individual json/urlencoded middlewares
 * @deprecated
 */
```

I'm not sure how this is fixed in terms of Typescript / Commenting but I can reference this issue to fix.

**Comment by hootyjeremy** [comment]
> I am getting this too when using typescript.
> 
> After doing some digging, it looks like it's coming from here,
> 
> https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/body-parser/index.d.ts#L19
> 
> After doing some more digging, there was an older comment:
> 
> ```
> /**
>  * bodyParser: use individual json/urlencoded middlewares
>  * @deprecated
>  */
> ```
> 
> I'm not sure how this is fixed in terms of Typescript / Commenting but I can reference this issue to fix.

Yeah, I noticed that all my includes were coming from local appdata Typescript. I must have done something wrong when setting up node maybe? I couldn't find an answer so i just uninstalled my node packages and made sure to reinstall them locally and that seemed to work for some reason.

Thanks. :D

**Comment by letmaik** [comment]
Tracked here: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/54252

**Comment by samarmohan** [comment]
Fixed in DefinitelyTyped/DefinitelyTyped#54254

**Comment by mendhak** [comment]
Looks like that PR's been closed without merging.  bodyParser still appears as deprecated.

**Comment by dougwilson** [comment]
Open issues in DefinitelyTyped, not here.
